### ISSUE TITLE
Deleted files

### ISSUE THREAD

**Issue by teej043** [moshisora/gulp-diff-build#6]
Does it take into account deleted files?
Because somehow when I deleted a file, the hash json didn't update which makes it ignore and detect that it did not seen any changes.

It seems to account new files though.

I'm using it on the gulp-iconfont task so it won't actually remake any icons if there are no changes in the svg (deleted, added, modified files) folder.

```
gulp.task('iconfont', function(){
  gulp.src(['src/svg/*.svg'])
    .pipe(diff({
      hash: 'iconfont'
    }))
    .pipe(iconfontcss({
      fontName: fontName,
      path: './node_modules/gulp-iconfont-css/templates/_icons.scss',
      targetPath: '../../sass/utilities/_icons.scss',
      fontPath: '../fonts/icons/'
    }))
    .pipe(iconfont({
      fontName: fontName,
      fixedWidth: true,
      centerHorizontally: true,
      normalize: true,
      fontHeight:1000,
      descent: 0
     }))
    .pipe(gulp.dest('src/fonts/icons/'));
});
```

**Comment by moshisora** [comment]
@teej043 

now, `gulp-diff-build` can't detect changing when any src files are deleted, and it'll be fixed on https://github.com/moshisora/gulp-diff-build/pull/7.
thank you!
